- name: configure MYSQL
  hosts: mysql
  become: yes
  vars:
    mysql_root_password: ExpenseApp@1
  tasks:
  - name: Install MySQL Server
    ansible.builtin.dnf:
      name: mysql-server
      state: installed
  
  - name: Start and enable mysql
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: Check the connection of mysql
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: mysql.deaws82s.online
    register: mysql_info
    ignore_errors: true

  - name: print output
    ansible.builtin.debug:
      msg: "{{ mysql_info }}"